
// Auto-generated by AutoPilot on 29-07-2023 at 20:39:26

const express = require('express');
const router = express.Router();

// Array of top 20 PS2 games
const ps2Games = [
  'Grand Theft Auto: San Andreas',
  'Metal Gear Solid 3: Snake Eater',
  'Resident Evil 4',
  'Final Fantasy X',
  'God of War',
  'Shadow of the Colossus',
  'Gran Turismo 4',
  'Devil May Cry 3',
  'Kingdom Hearts II',
  'Okami',
  'Ratchet & Clank: Up Your Arsenal',
  'Burnout 3: Takedown',
  'Jak 3',
  'Tekken 5',
  'Mafia: The City of Lost Heaven',
  'Sly 2: Band of Thieves',
  'Guitar Hero II',
  'Katamari Damacy',
  'Burnout Revenge',
  'SOCOM II: U.S. Navy SEALs'
];

// Route for API
router.get('/ps2Games', (req, res) => {
  // Get random index from array
  const randomIndex = Math.floor(Math.random() * ps2Games.length);
  // Return random game
  res.status(200).send(ps2Games[randomIndex]);
});

module.exports = router;